account/urls.py
from django.urls import path
from . import views


app_name = 'account'
urlpatterns = [
    path('login/', views.login_user, name='login_user'),
    path('register/', views.register_user, name='register_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('user_dashboard/<int:user_id>/', views.user_dashboard, name='user_dashboard'),
    path('edit_profile/<int:user_id>/', views.edit_profile, name='edit_profile'),
    path('follow/', views.follow, name='follow'),
    path('unfollow/', views.unfollow, name='unfollow'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls', namespace='post')),
    path('account/', include('account.urls', namespace='account')),
]

post/urls.py
from django.urls import path
from . import views

app_name = 'post'
urlpatterns = [
    path('', views.all_posts, name='all_posts'),
    path('post/<slug:slug>/<int:id>/', views.detail_post, name='detail_post'),
    path('add_post/<int:user_id>/', views.add_post, name='add_post'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
    path('edit_post/<int:post_id>/<int:post_user_id>', views.edit_post, name='edit_post'),
    path('reply/<int:comment_id>/<int:post_id>/', views.add_reply, name='add_reply'),
]

post/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Post(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField(max_length=400)
    slug = models.SlugField(max_length=20)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.user} write {self.body[:20]}'
    
    class Meta:
        ordering = ('created_at',)

    def get_absolute_url(self):
        return reverse('post:detail_post', args=[self.slug, self.id])


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='ucomment')
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='pcomment')
    reply = models.ForeignKey('self', on_delete=models.CASCADE, null=True, blank=True, related_name='rcomment')
    is_reply = models.BooleanField(default=False)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} send comment to {self.post}'

post/forms.py
from django import forms
from .models import Post, Comment

class Add_EditPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('body',)


class Add_Commen_Add_Reply_Form(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('body',)

post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.utils.text import slugify
from django.contrib import messages
from .models import Post, Comment
from .forms import Add_EditPostForm, Add_Commen_Add_Reply_Form

def all_posts(request):
    posts = Post.objects.all()
    return render(request, 'post/all_posts.html', {'posts': posts})


def detail_post(request, slug, id):
    post = get_object_or_404(Post, slug=slug, id=id)
    comments = post.pcomment.all() # == Comment.objects.filter(post=post)
    if request.method == 'POST':
        form = Add_Commen_Add_Reply_Form(request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = post
            new_comment.save()
            messages.success(request, 'Comment successfully sent')
            return redirect('post:detail_post', slug, id)
    else:
        form = Add_Commen_Add_Reply_Form()
    context = {
    'post': post,
    'comments': comments,
    'form': form,
    }
    return render(request, 'post/detail_post.html', context)


@login_required
def add_post(request, user_id):
    user = User.objects.get(id=user_id)
    if request.method == 'POST':
        form = Add_EditPostForm(request.POST)
        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.user = user
            new_post.slug = slugify(form.cleaned_data['body'][:20])
            new_post.save()
            return redirect('account:user_dashboard', user_id)
    else:
        form = Add_EditPostForm()
    return render(request, 'post/post_app_forms.html', {'form': form})


@login_required
def delete_post(request, post_id):
    post = Post.objects.get(pk=post_id)
    user_id = post.user.id  #for return to user dashboard
    post.delete()
    return redirect('account:user_dashboard', user_id)


@login_required
def edit_post(request, post_id, post_user_id):
    post = get_object_or_404(Post, id=post_id)
    user = get_object_or_404(User, id=post_user_id) #for set user
    if request.method == 'POST':
        form = Add_EditPostForm(request.POST, instance=post)
        if form.is_valid():
            edit_post = form.save(commit=False)
            edit_post.user = user
            edit_post.slug = slugify(form.cleaned_data['body'][:20])
            edit_post.save()
            return redirect('account:user_dashboard', post_user_id)
    else:
        form = Add_EditPostForm(instance=post)
    return render(request, 'post/post_app_forms.html', {'form': form})


def add_reply(request, comment_id, post_id):
    post = get_object_or_404(Post, id=post_id)
    comment = get_object_or_404(Comment, id=comment_id, reply='False')
    if request.method == 'POST':
        form = Add_Commen_Add_Reply_Form(request.POST)
        if form.is_valid():
            new_reply = form.save(commit=False)
            new_reply.user = request.user
            new_reply.post = post
            new_reply.reply = comment
            new_reply.is_reply = True
            new_reply.save()
            messages.success(request, 'reply successfuly sended')
            return redirect('post:detail_post', post.slug, post_id)
    else:
        return redirect('post:all_post')

post/templates/post/all_posts.html
{% extends 'base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="card">
            <div class="card-header">
                <a href="{% url 'account:user_dashboard' post.user.id %}"><h4>{{ post.user }}</h4></a>
            </div>
            <div class="card-body">
                <a href="{{ post.get_absolute_url }}"><h5 class="card-title">{{ post.body|slice:":20" }}...</h5></a>
            </div>
        </div><br>
    {% endfor %}
{% endblock %}

post/templates/post/detail_post.html
{% extends 'base.html' %}
{% block content %}
    <b>{{ post.user|title }}</b><br><br>
    <p>{{ post.body|title }}</p>
    <small>{{ post.created_at }}</small><br><br>
    {% if request.user == post.user %}
        <a href="{% url 'post:delete_post' post.id %}" class='btn btn-danger'>Delete</a>
        <a href="{% url 'post:edit_post' post.id post.user.id %}" class='btn btn-warning'>Edit</a>
        <br>
    {% endif %}
    <br><hr>
    <h5>Comments:</h5>
    <small>{{comments.count}} comment</small><br><br>
    {% if request.user.is_authenticated %}
        <form action="" method="post">
            {% csrf_token %}{{ form.as_p }}
            <input type="submit" value="send" class="btn btn-success">
        </form><br><hr>
    {% else %}
    <p>If you like write comment you need to login or register</p>
    <hr>
    {% endif %}
    {% for comment in comments %}
    <br>
        <div class="card bg-dark text-light">
            <div class="card-body">
            <h5 class="card-title">{{ comment.user }}</h5>
            <h6 class="card-subtitle mb-2 text-muted">{{ comment.created_at }}</h6>
            <p class="card-text">{{ comment.body }}</p>
            </div>
            {% if request.user.is_authenticated %}
                <form  action="{% url 'post:add_reply' comment.id post.id %}" method="post">
                    {% csrf_token %} {{ form.as_p }}
                    <input type="submit" value="send" class="btn btn-secondary">
                </form>
            {% endif %}
            {% for reply in comment.rcomment.all %}
            <div class="card text-dark">
                <div class="card-body">
                    <h6 class="card-title">{{ reply.user }} to {{ comment.user }}:</h6>
                    <p class="card-text">{{ reply.body }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    {% endfor %}
{% endblock %}

post/templates/post/post_app_forms.html
{% extends 'base.html' %}


{% block content %}
<form action="" method="post">
    {% csrf_token %} {{form.as_p}}
    <input type="submit" value="submit">
</form>
{% endblock %}