account/urls.py
from django.urls import path
from . import views


app_name = 'account'
urlpatterns = [
    path('login/', views.login_user, name='login_user'),
    path('register/', views.register_user, name='register_user'),
    path('logout/', views.logout_user, name='logout_user'),
    path('user_dashboard/<int:user_id>/', views.user_dashboard, name='user_dashboard'),
    path('edit_profile/<int:user_id>/', views.edit_profile, name='edit_profile'),
    path('follow/', views.follow, name='follow'),
    path('unfollow/', views.unfollow, name='unfollow'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('post.urls', namespace='post')),
    path('account/', include('account.urls', namespace='account')),
]

post/urls.py
from django.urls import path
from . import views

app_name = 'post'
urlpatterns = [
    path('', views.all_posts, name='all_posts'),
    path('post/<slug:slug>/<int:id>/', views.detail_post, name='detail_post'),
    path('add_post/<int:user_id>/', views.add_post, name='add_post'),
    path('delete_post/<int:post_id>/', views.delete_post, name='delete_post'),
    path('edit_post/<int:post_id>/<int:post_user_id>', views.edit_post, name='edit_post'),
    path('reply/<int:comment_id>/<int:post_id>/', views.add_reply, name='add_reply'),
]

templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
    <div class="alert alert-primary" role="alert">
        {{ message }}
    </div>
    {% endfor %}
{% endif %}

templates/inc/nav.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <a class="nav-item nav-link active" href="{% url 'post:all_posts' %}">Home</a>
        {% if request.user.is_authenticated %}
        <a class="nav-item nav-link active" href="{% url 'account:logout_user' %}">Logout</a>
        <a class="nav-item nav-link active" href="{% url 'account:user_dashboard' request.user.id %}">{{request.user}} Profile</a>
        {% else %}
        <a class="nav-item nav-link active" href="{% url 'account:login_user' %}">Login</a>
        <a class="nav-item nav-link active" href="{% url 'account:register_user' %}">Register</a>
        {% endif %}
      </div>
    </div>
</nav>